apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: test2-deploy
spec:
 replicas: 10
 template:
  metadata:
    labels:
       app: test2-app
  spec:
   containers:
   - name: test2-pod
     image: jenkins
     ports:
     - containerPort: 9090
